#!/bin/bash

# Client to cpucsekk_server
# Stand in queue
# Tell us why

inicheck=0.5	#Initial wait in queue. Better the server acts first if it can.
checkint=1	#How often to look into queue
ourpid=$$

echo "$ourpid" >> /tmp/cpucsekk_$USER/cpucsekk_queue
sleep $inicheck

while true
do
 #If we find our own pid:
 if grep -q "$ourpid" /tmp/cpucsekk_$USER/cpucsekk_queue
 then
  tellwhy=`cat "/tmp/cpucsekk_$USER/cpucsekk_why"`
  ourpos=`grep -n "$ourpid" /tmp/cpucsekk_$USER/cpucsekk_queue|cut -f1 -d:`
  #echo "ourpos: $ourpos"
  if [[ $ourpos > 1 ]]
  then
   echo "pos: $ourpos	$tellwhy"
  else
   if [[ "$tellwhy" != "" ]]
   then
    echo "$tellwhy"
   fi
  fi
  read -t $checkint -p "" ki
  if [[ "$cseen" != "1" ]]
  then
   echo "cpucsekk: press c [enter] to skip."
  fi
  if [ "$ki" == "c" ]; then
   break
  fi
  cseen=1
 #If we don't find our own pid then terminate
 else
  break
 fi
done
