#!/bin/bash

dbok=0

while [ $dbok -lt 3 ]; do
 command -v dropbox-cli > /dev/null 2>&1
 if [ "$?" -ne "0" ]
 then
  dbst=`dropbox status`
 else
  dbst=`dropbox-cli status`
 fi
 ido=`date +%T`
 echo "$ido Dropbox: $dbst	; $dbok"
 if [[ "$dbst" == "Idle" ]] || [[ "$dbst" == "Up to date" ]]; then
  let dbok=dbok+1
 else
  let dbok=0
 fi 
 if [ $dbok == 0 ]; then
  ki="n"
  read -t 5 -p "Skip dbst? s" ki
  if [ "$ki" == "s" ]; then
   break
  fi
 fi
 if [[ $dbok == 1 ]] || [[ $dbok == 2 ]]; then
  sleep 1
 fi
done
