#!/bin/bash

# Gets the heaviest job from top, if above certain threshold.
cpupc=15	# Percent of cpu load (combined across each cores) to hold cpucsekk, see inside the script cpucsekk_server.

if [ -f $HOME/.cpucsekk/cpucsekk_params.txt ]
then

 # Remove spaces, pick line starting with cpupc
 cpupcline=$(sed "s/ //g" $HOME/.cpucsekk/cpucsekk_params.txt|grep "^\bcpupc\b")
 if [[ "$cpupcline" != "" ]]
 then
  # Expand after last =
  rawcpupc=${cpupcline##*=}
  #Check what we got
  checkcpupc=`echo "$rawcpupc" | grep -E ^\-?[0-9]*\.?[0-9]+$`
  if [[ "$checkcpupc" == "" ]]
  then
   echo "cpupc should be a number, skipping $cpupcline in $HOME/.cpucsekk/cpucsekk_params.txt"
  else
   cpupc="$rawcpupc"
  fi
 fi
fi

# Get top percentage and name of process
topoutp=`top -b -n1 |
awk '{
# We set the relevant column numbers further down. If they are set then print from the next line and exit.
 if (commcol>0){
  printf "%d ",$cpucol
  printf $commcol
  exit
 }
# Setting relevant column numbers here.
 for (i=1; i<=NF; i++){
  if ($i=="%CPU"){
   cpucol=i
  }
  if ($i=="COMMAND"){
   commcol=i
  }
 } 
}'`

topp=${topoutp% *}
topn=${topoutp#* }
## Test:
#echo "$topoutp"
#echo "topp: $topp"
#echo "$topn"
#echo "cpupc: $cpupc"

if [[ $topp -gt $cpupc ]]
then
 echo "$topn $topp%"
fi
